### ISSUE TITLE
Fix server

### ISSUE THREAD

**Issue by 0x6a73** [Dante383/sicario#1]
I have no other means to contact you and the server is currently completely broken. Any idea what's happening?

**Comment by Dante383** [comment]
I just told genericTrigger to message you on wykop. By some reason, the server doesn't not want to connect to the router - I will fix it tomorrow, around 3 PM because I will have to go to the server, this cannot be done remotely

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by 0x6a73** [comment]
Thanks. Also, I'll send you new server somewhere around friday.

**Comment by Dante383** [comment]
Great, nice to know. Ty

Sent from ProtonMail mobile

-------- Original Message --------
